'use client';
import {FormEvent,useEffect,useState} from 'react';
import {createClient} from '@/lib/supabase/client';
import {useRouter} from 'next/navigation';

type Client={id:string;name:string;whatsapp:string|null;plan:string|null;amount:number;due_date:string|null;status:string};
export default function Clients(){const router=useRouter();const [rows,setRows]=useState<Client[]>([]);const [org,setOrg]=useState('');const [name,setName]=useState('');const [whatsapp,setWhatsapp]=useState('');const [plan,setPlan]=useState('');const [amount,setAmount]=useState('');const [due,setDue]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const supabase=createClient();
async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return}const {data:m}=await supabase.from('organization_members').select('organization_id').eq('user_id',user.id).limit(1);if(m?.[0]){setOrg(m[0].organization_id);const {data}=await supabase.from('clients').select('*').eq('organization_id',m[0].organization_id).order('created_at',{ascending:false});setRows(data??[])}setLoading(false)}useEffect(()=>{load()},[]);
async function add(e:FormEvent){e.preventDefault();if(!org)return;setSaving(true);await supabase.from('clients').insert({organization_id:org,name,whatsapp,plan,amount:Number(amount||0),due_date:due||null});setName('');setWhatsapp('');setPlan('');setAmount('');setDue('');setSaving(false);load()}
return <main className="dashboard"><header><div className="brand"><span>GP</span><div><strong>GestorPro</strong><small>2.0</small></div></div><a href="/dashboard" style={{color:'#c4b5fd'}}>Dashboard</a></header><section className="hero"><p className="eyebrow">CLIENTES</p><h1>Clientes</h1><p>Cadastre e acompanhe suas assinaturas.</p></section><form onSubmit={add} className="auth-card" style={{margin:'0 5% 25px',maxWidth:'none'}}><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:12}}><label>Nome<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>WhatsApp<input value={whatsapp} onChange={e=>setWhatsapp(e.target.value)}/></label><label>Plano<input value={plan} onChange={e=>setPlan(e.target.value)} placeholder="Mensal"/></label><label>Valor<input type="number" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Vencimento<input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><button disabled={saving} style={{alignSelf:'end',height:44}}>{saving?'Salvando...':'Adicionar cliente'}</button></div></form><section style={{margin:'0 5%',overflowX:'auto'}}>{loading?<p>Carregando...</p>:rows.length===0?<div className="empty" style={{margin:0}}><h2>Nenhum cliente cadastrado</h2><p>Use o formulário acima para adicionar o primeiro cliente.</p></div>:<table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr><th style={{textAlign:'left',padding:12}}>Nome</th><th style={{textAlign:'left',padding:12}}>WhatsApp</th><th style={{textAlign:'left',padding:12}}>Plano</th><th style={{textAlign:'left',padding:12}}>Valor</th><th style={{textAlign:'left',padding:12}}>Vencimento</th><th style={{textAlign:'left',padding:12}}>Status</th></tr></thead><tbody>{rows.map(c=><tr key={c.id}><td style={{padding:12}}>{c.name}</td><td style={{padding:12}}>{c.whatsapp||'-'}</td><td style={{padding:12}}>{c.plan||'-'}</td><td style={{padding:12}}>R$ {Number(c.amount).toFixed(2).replace('.',',')}</td><td style={{padding:12}}>{c.due_date||'-'}</td><td style={{padding:12}}>{c.status}</td></tr>)}</tbody></table>}</section></main>}
